Description: This cloud formation Template deals with the deployment of MRBS(Meeting Room Booking System) application.The template comprises of 3 substacks(Network Stack,ALB Stack,RDS stack).The MRBS application uses MYSQL Database which is integrated in RDS Stack.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: MRBS APP

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.0.0.0/16
  
  KeyName:
    Description: Key name for resource creation
    Type: String
    Default: arunkumarkeypair
  
  ImageId:
    Description: AMI Id for ec2 instance creation
    Type: String
    Default : ami-0c293f3f676ec4f90   #ami id mappings for each region.
  
  InstanceType:
    Description: Instance Type for ec2 instance creation
    Type: String
    Default : t2.micro              #instance type
  
  DBClass:
    Description: Database instance class
    Type: String
    Default: db.t2.micro
    
  DBInstance:
    Description: DB Instance for RDS
    Type: String
    Default: mrbs

  DBPassword:
    Description: DB Password
    Type: String
    Default: mrbs-password 
  
  DBUser:
    Description: DB User
    Type: String
    Default: mrbs
  
  DBName:
    Description: DB Name
    Type: String
    Default: mrbs

  MultiAZDb:
    Default: 'false'
    Description: Create a Multi-AZ MySQL Amazon RDS database instance
    Type: String
    AllowedValues:
      - 'true'
      - 'false'



Resources:
  NetworkSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://mrbs-substacks.s3.amazonaws.com/networkstack.yaml
      Parameters:
        EnvironmentName : !Ref  EnvironmentName
        VpcCIDR : !Ref VpcCIDR

  RDSSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://mrbs-substacks.s3.amazonaws.com/rdsstack.yaml
      Parameters:
        EnvironmentName : !Ref  EnvironmentName
        VpcCIDR : !Ref VpcCIDR 
        DBUser: !Ref DBUser
        DBName: !Ref DBName
        DBPassword: !Ref DBPassword  
        VPC : !GetAtt NetworkSubStack.Outputs.VPC
        PrivateSubnet3 : !GetAtt NetworkSubStack.Outputs.PrivateSubnet3
        PrivateSubnet4 : !GetAtt NetworkSubStack.Outputs.PrivateSubnet4
          
  ALBSubStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://mrbs-substacks.s3.amazonaws.com/albstack.yaml
      Parameters:
        EnvironmentName : !Ref  EnvironmentName
        ImageId: !Ref ImageId
        KeyName : !Ref KeyName
        InstanceType : !Ref InstanceType
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        VPC : !GetAtt NetworkSubStack.Outputs.VPC
        PublicSubnet1 : !GetAtt NetworkSubStack.Outputs.PublicSubnet1
        PublicSubnet2 : !GetAtt NetworkSubStack.Outputs.PublicSubnet2
        PrivateSubnet1 : !GetAtt NetworkSubStack.Outputs.PrivateSubnet1
        PrivateSubnet2 : !GetAtt NetworkSubStack.Outputs.PrivateSubnet2
        RDSHost: !GetAtt RDSSubStack.Outputs.RDSHost



Outputs:
  WebsiteURL:
      Value: !GetAtt ALBSubStack.Outputs.WebsiteURL
      Description : Endpoint of MRBS application  